//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simulador {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simulador.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificar a documentação para obter informações de como utilizar e caraterísticas do software..
        /// </summary>
        internal static string STR_AJUDA {
            get {
                return ResourceManager.GetString("STR_AJUDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (START|END|BYTE|WORD|RESB|RESW|EXTDEF|EXTREF|EQU|CSECT|BASE|NOBASE|LTORG).
        /// </summary>
        internal static string STR_DIRETIVAS {
            get {
                return ResourceManager.GetString("STR_DIRETIVAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo Assembly(*.asm)|*.asm|Arquivo de Texto(*.txt)|*.txt|Arquivo Objeto(*.obj)|*.obj|Todos os arquivos (*.*)|*.*.
        /// </summary>
        internal static string STR_FILTRO {
            get {
                return ResourceManager.GetString("STR_FILTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo de Texto(*.txt)|*.txt|Todos os arquivos (*.*)|*.*.
        /// </summary>
        internal static string STR_FILTRO_DADOS {
            get {
                return ResourceManager.GetString("STR_FILTRO_DADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ADD|ADDR|AADF|AND|CLEAR|COMP|COMPR|COMPF|DIV|DIVF|DIVR|FIX|FLOAT|HIO|J|JEQ|JGT|JLT|JSUB|LDA|LDB|LDCH|LDF|LDL|LDS|LDT|LDX|LPS|MUL|MULF|MULR|NORM|OR|RD|RMO|RSUB|SHIFTL|SHIFTR|SIO|SSK|STA|STB|STCH|STI|STF|STL|STS|STSW|STT|STX|SUB|SUBF|SUBR|SVC|TD|TIO|TIX|TIXR|WD).
        /// </summary>
        internal static string STR_INSTRUCOES {
            get {
                return ResourceManager.GetString("STR_INSTRUCOES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ADD|AND|COMP|DIV|HIO|J|JEQ|JGT|JLT|JSUB|LDA|LDCH|LDL|LDX|MUL|OR|RD|RMO|RSUB|SHIFTL|SHIFTR|SIO|SSK|STA|STB|STCH|STF|STL|STSW|STT|STX|SUB|SVC|TD|TIO|TIX|WD).
        /// </summary>
        internal static string STR_PADRAO_SIC {
            get {
                return ResourceManager.GetString("STR_PADRAO_SIC", resourceCulture);
            }
        }

        internal static string STR_MIF_COMMENT
        {
            get
            {
                return ResourceManager.GetString("STR_MIF_COMMENT", resourceCulture);
            }
        }
    }
}
